# Generated by Django 3.1.5 on 2021-01-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expensesapp', '0002_auto_20210129_0136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='categorytype',
            field=models.CharField(choices=[('Unknown', 'Unknown'), ('Income', 'Income'), ('Expense', 'Expense')], default='Unknown', max_length=10),
        ),
    ]
