# Generated by Django 3.1.5 on 2021-01-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpreference',
            options={'verbose_name_plural': 'User Preference'},
        ),
    ]
